// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkAoYqDE11O7QLu4BHaTpmOQgoadnZqmI',
    appId: '1:535945239801:web:cc38e3640998a58b909628',
    messagingSenderId: '535945239801',
    projectId: 'minha-gestacao-4af55',
    authDomain: 'minha-gestacao-4af55.firebaseapp.com',
    storageBucket: 'minha-gestacao-4af55.firebasestorage.app',
    measurementId: 'G-1E5PEXKSW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPiXSxtE82741Jhu4kI4HNbweCJLp6I_c',
    appId: '1:535945239801:android:f9512c8918af63e3909628',
    messagingSenderId: '535945239801',
    projectId: 'minha-gestacao-4af55',
    storageBucket: 'minha-gestacao-4af55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5KcEw5RqaC298_jd0m7RvyOi7NQGG2oc',
    appId: '1:535945239801:ios:ddbeb3c5c65f0996909628',
    messagingSenderId: '535945239801',
    projectId: 'minha-gestacao-4af55',
    storageBucket: 'minha-gestacao-4af55.firebasestorage.app',
    iosBundleId: 'com.example.suacontracaoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5KcEw5RqaC298_jd0m7RvyOi7NQGG2oc',
    appId: '1:535945239801:ios:ddbeb3c5c65f0996909628',
    messagingSenderId: '535945239801',
    projectId: 'minha-gestacao-4af55',
    storageBucket: 'minha-gestacao-4af55.firebasestorage.app',
    iosBundleId: 'com.example.suacontracaoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkAoYqDE11O7QLu4BHaTpmOQgoadnZqmI',
    appId: '1:535945239801:web:9f7463bd3ce8708a909628',
    messagingSenderId: '535945239801',
    projectId: 'minha-gestacao-4af55',
    authDomain: 'minha-gestacao-4af55.firebaseapp.com',
    storageBucket: 'minha-gestacao-4af55.firebasestorage.app',
    measurementId: 'G-TPTDQ17230',
  );
}
